# Generated by Django 5.1rc1 on 2024-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_seat_number_alter_seat_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
